[package]
name = "pacord"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
toml = "0.8"
evdev = "0.12"
input-linux = "0.7"
gilrs = "0.10"
eframe = "0.28"
egui = "0.28"
log = "0.4"
env_logger = "0.11"
